## enable bash environment
#set-option -g default-shell /bin/bash
#set-option -g default-command /bin/bash

#set-option -g default-shell /usr/local/bin/fish
#set-option -g default-command  /usr/local/bin/fish


#set mouse scroll not following disable copy from clipboard by using mouse.
#setw -g mouse on



## Use vim keybindings in copy mode
setw -g mode-keys vi
#set-option -s set-clipboard off
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -se c -i'


## set history
set-option -g history-limit 5000

bind-key -r -T prefix p resize-pane -U 3
bind-key -r -T prefix . resize-pane -D 3
bind-key -r -T prefix h resize-pane -L 3
bind-key -r -T prefix l resize-pane -R 3

bind-key -r -T prefix P resize-pane -U 20
bind-key -r -T prefix > resize-pane -D 20
bind-key -r -T prefix H resize-pane -L 30
bind-key -r -T prefix L resize-pane -R 30

# Advertise 256 colors
#set -g default-terminal "tmux-256color"

# Enable truecolor (24-bit)
#set-option -ga terminal-overrides ",xterm-256color:Tc"

